### ISSUE TITLE
Not loading in WSL2 with Ubuntu 20.04

### ISSUE THREAD

**Issue by JeroenvdV** [thanhlmm/refi-app#10]
I've installed the deb release 0.10 in an Ubuntu 20.04 instance on Windows 11 with WSL2. In this same instance, I can run GIMP for example and the GUI will work. With Refi App, it does not fully start up. Is there anything more I can do to make this work? I have attached a screenshot. The full-screen window belongs to refi-app.
![2021-11-30 14_16_00-Refi App (Ubuntu-20 04)](https://user-images.githubusercontent.com/5629916/144054460-453f10e3-8455-4a2c-a3b6-e009bba13c90.png)

**Comment by thanhlmm** [comment]
Hi, I believe you need to run the frontend.

Here is the instruction for setting up development env: https://github.com/thanhlmm/refi-app/blob/main/DEVELOPMENT.md
