### ISSUE TITLE
Notion help page access

### ISSUE THREAD

**Issue by andreluisfc** [thanhlmm/refi-app#100]
When click on "I dont' know how to get credential file" i've got redirected to a notion page but its not public.

![image](https://user-images.githubusercontent.com/80536789/227263748-4b388f71-44e4-4997-a263-41139edec986.png)
![image](https://user-images.githubusercontent.com/80536789/227263793-96ac8dca-6951-4b6f-83fc-96f50ec299fe.png)

**Comment by thanhlmm** [comment]
Hi thank you for your report, can you check again @andreluisfc ?

**Comment by andreluisfc** [comment]
Solved.

Thanks!!

**Comment by Fraggle** [comment]
FYI, It seems broken again.
