### ISSUE TITLE
Fatal Layout issue on Linux

### ISSUE THREAD

**Issue by pmullot** [thanhlmm/refi-app#15]
I've downloaded and installed v0.0.10. No problem at that point.
When I launch the app, a greyish window appears with a dialog *half hidden* on the right side to choose credentials
The main window is resizable but doing so doesn't allow the dialog to appear. It sticks to the right edge, making the app useless, which is a shame because it looks really promissing!!

![image](https://user-images.githubusercontent.com/75703/144283647-26b34da6-e3ed-41f9-bb6b-a12078336342.png)

My box:
System:    Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 4.8.6 
           wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 

Machine:   Type: Laptop System: HP product: HP ZBook 14u G5 v: N/A serial: <filter> Chassis: 
           type: 10 serial: <filter> 
           Mobo: HP model: 83B2 v: KBC Version 04.53.00 serial: <filter> UEFI [Legacy]: HP 
           v: Q78 Ver. 01.03.00 date: 07/18/2018 

CPU:      Topology: Quad Core model: Intel Core i7-8650U bits: 64 type: MT MCP arch: Kaby Lake 
           rev: A L2 cache: 8192 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 33599 
           Speed: 800 MHz min/max: 400/4200 MHz Core speeds (MHz): 1: 800 2: 800 3: 800 4: 800 
           5: 800 6: 800 7: 799 8: 800 

Graphics:  Device-1: Intel UHD Graphics 620 vendor: Hewlett-Packard driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:5917 
           Device-2: AMD Lexa XT [Radeon PRO WX 3100] vendor: Hewlett-Packard driver: amdgpu 
           v: kernel bus ID: 01:00.0 chip ID: 1002:6985 
           Display: x11 server: X.Org 1.20.11 driver: amdgpu,ati,modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz, 1280x1024~60Hz, 1280x1024~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 21.0.3 
           direct render: Yes

**Comment by thanhlmm** [comment]
Hi, thanks for the report

This looks weird and It takes time for me to reproduce it, so please stay tuned

**Comment by RickRyan26** [comment]
Same problem, looking forward to the fix 👍

**Comment by thanhlmm** [comment]
Hi @pmullot @RickRyan26 

https://dl.todesktop.com/211201njqikvxkx/builds/211208i3mvsqrbs

This is beta build for the fixing, would you mind help me try it and confirm does this build really help?

**Comment by pmullot** [comment]
Hi,

It's better, but still some errors showing up...
[refi-app-0.0.10-build-211208i3mvsqrbs.AppImage.log](https://github.com/thanhlmm/refi-app/files/7678618/refi-app-0.0.10-build-211208i3mvsqrbs.AppImage.log)

- The min/max/close buttons on the top right side doesn't work for example
- The link for "I don't know how to get credential file" doesn't open any browser window nor shows anything


But the dialog position is fixed (once you resize the window once)

The rest of the features seems to work properly.
![image](https://user-images.githubusercontent.com/75703/145277822-fe73f99b-79db-42b2-b1f1-5a8e25376057.png)

**Comment by pmullot** [comment]
Thanks for the feedback!

At first, when the app starts, it's maximized and half its window is white.
I have to double click on the top bar to un-maximize it. At this point,
everything looks great.
I can maximize again double clicking on the top bar but when I hover the
mouse on top of the min/max/close buttons, the icon doesn't change to
pointer (still arrow) and clicking has no effect.

To close the app, I have to terminate the process.

**Comment by thanhlmm** [comment]
Fixed in v0.0.11
