### ISSUE TITLE
Unable to develop on M1 mac

### ISSUE THREAD

**Issue by sanketkheni01** [thanhlmm/refi-app#21]
<img width="568" alt="Screenshot 2021-12-06 at 11 18 05 AM" src="https://user-images.githubusercontent.com/68942390/144794108-c1752fcb-c4e7-4057-93ed-5f97d7d9dae1.png">

I am trying to run the build command in tree but it's saying it does not exist in the package.json
So I tried to run  `npx father build` After that I got the 2 folders `lib and es` in the tree folder. and after that I run

`yarn dev` in vite folder

<img width="566" alt="Screenshot 2021-12-06 at 11 21 46 AM" src="https://user-images.githubusercontent.com/68942390/144794497-98d828a0-204d-478f-b3d8-d96d05093b73.png">

I want to contribute to this project.

**Comment by thanhlmm** [comment]
Hi @sanketkheni01 

I'm happy that you want to contribute to the project. Which part do you want to contribute?

I believe you need to run yarn again on `vite` folder to make sure everything is good. Here are the complete steps to set up development https://github.com/thanhlmm/refi-app/blob/main/DEVELOPMENT.md.

Basically, we will need to build 2 libraries: `rc-tree` and firestore-serialzier` before install `vite` dependencies

**Comment by thanhlmm** [comment]
Hey, I'm sorry for the misleading command. You should run
```
yarn compile
```
In `tree` folder to build

**Comment by sanketkheni01** [comment]
Can you please provide which node version, python version, and os you are using? I am getting errors while running yarn command in server it's something related to node-gyp

**Comment by sanketkheni01** [comment]
Node 17 was the problem. switched to 14 and now everything just worked.
