### ISSUE TITLE
BUG: Button "I don't know how to get credential file" doesn't work on Windows

### ISSUE THREAD

**Issue by Berki2021** [thanhlmm/refi-app#22]
### BUG REPORT

The Button"I don't know how to get credential file" doesn't work on Windows. When clicking at the button, nothing happens.

### Expected Behavior

The Button should open a site etc. to show how to get the credentials

### System

Windows 10 Pro 64Bit
Version 0.0.9

### Screenshot

![grafik](https://user-images.githubusercontent.com/65120636/145010255-01794e37-6f5e-4626-b5bc-5712562604fb.png)

**Comment by thanhlmm** [comment]
Hey thanks for the report, I know the issue and will make a fix on the next version.

You can use this link temporary: https://www.notion.so/cuthanh/53dd3a24048c467986e1ab1a39459547?v=e336f8b7d9b84e0881c6f262adb14998

**Comment by Berki2021** [comment]
> 

Okay thanks

**Comment by thanhlmm** [comment]
What's new on the bottom is dead also. Need to fix in the next version
