### ISSUE TITLE
BUG: Windows Button "Minimizing, Closing, Adding new Tab" not working

### ISSUE THREAD

**Issue by Berki2021** [thanhlmm/refi-app#23]
### BUG REPORT

When trying to click on any button at the top of the app (e.g "Add Tab (+)", Close App (x), Minimize (-) etc.) nothing happens. The app needs to be closed via "Task bar > Right click app > close". Minimizing only works when double-clicking the menu bar.

### Expected Behavior

The Buttons should work and the user should be able to add a new tab, close the app, minimize it etc.

### System

Windows 10 Pro 64Bit
Version 0.0.9

### Screenshot
![grafik](https://user-images.githubusercontent.com/65120636/145014351-41314532-e7a1-4d59-8fe9-773d2c53a84c.png)

**Comment by thanhlmm** [comment]
That weird, let me try in the window 10 simulator. Thanks for your report

**Comment by thanhlmm** [comment]
<img width="1682" alt="Screen Shot 2021-12-08 at 12 07 00 PM" src="https://user-images.githubusercontent.com/9281080/145151543-633ea08c-7f21-4d32-89db-f7098f759eeb.png">

The issue happens for large screen and resize to smaller ones. Might be styles issue
