### ISSUE TITLE
Feature Request: Add "Delete Button" behind a row or at the right side

### ISSUE THREAD

**Issue by Berki2021** [thanhlmm/refi-app#24]
### Feature Request

Currently, it is only possible to delete a row/document by "right-clicking it on the left nav-menu > delete document". Maybe there should be another button at the end of the row or on the right side, to faster delete the menu"

### Screenshot
![grafik](https://user-images.githubusercontent.com/65120636/145015349-396ab02d-5a3c-42b6-a7d9-3f96747a6e59.png)

**Comment by thanhlmm** [comment]
Hey I think the delete button on the editor pannel should be good. But it will not solve your case when you want to delete mass amount of documents

**Comment by Berki2021** [comment]
> Hey I think the delete button on the editor pannel should be good. But it will not solve your case when you want to delete mass amount of documents

What happens when you delete an entire collection? Is every document in there deleted aswell?

**Comment by thanhlmm** [comment]
Yes, when we delete the collection, all its children gone also

**Comment by Berki2021** [comment]
Okay then this can be closed
