### ISSUE TITLE
BUG: Columns don't refresh when importing data (sometime)

### ISSUE THREAD

**Issue by Berki2021** [thanhlmm/refi-app#28]
### BUG REPORT

When importing data (in my case JSON) the columns did not refresh themselves. Some do show the columns, some not.

### Screenshot (not showing column)

![grafik](https://user-images.githubusercontent.com/65120636/145032227-31c190e1-62c1-4a04-88cf-033222ef1e98.png)

### Screenshot (showing column)

![grafik](https://user-images.githubusercontent.com/65120636/145032657-fb596c14-707f-4adf-86d6-7647f71a7c0b.png)

**Comment by thanhlmm** [comment]
It seems like a bug. But you can work around by clicking: Properties -> Reset button

![image](https://user-images.githubusercontent.com/9281080/145046869-7f4d8ca9-5eda-407e-8859-0c66888e903d.png)

**Comment by Berki2021** [comment]
> It seems like a bug. But you can work around by clicking: Properties -> Reset button

That worked, thank you! But the bug should be fixed :D
