### ISSUE TITLE
Feature Request: Add manual refresh button

### ISSUE THREAD

**Issue by Berki2021** [thanhlmm/refi-app#29]
### Feature Request

Sometimes the data inside refi-app and the real firebase-data are not the same (out of sync). There should be a button to manually refresh the data. Currently, I am closing the app and restarting it, so it gets the new data.

### Current Behavior

App needs to be restarted in order to get the newest data sometimes

### Wanted Behavior

There should be a refresh-button to get the newest data

**Comment by thanhlmm** [comment]
Hey you can refresh by press
Cmd + R

**Comment by Berki2021** [comment]
> Hey you can refresh by press Cmd + R

Thanks! But should also be added to a button

**Comment by thanhlmm** [comment]
![image](https://user-images.githubusercontent.com/9281080/145201926-44cf303f-4355-40d1-87b8-b734327e9927.png)
Hey @Berki2021 , There is a button next to path input!

**Comment by Berki2021** [comment]
> ![image](https://user-images.githubusercontent.com/9281080/145201926-44cf303f-4355-40d1-87b8-b734327e9927.png) Hey @Berki2021 , There is a button next to path input!

Why does it say "revert changes"

**Comment by thanhlmm** [comment]
The word my miss-leading. Maybe we can change it to Refresh (It will revert all changes)

Do you want to make a contribution to this small fix?

**Comment by Berki2021** [comment]
> The word might miss-leading. Maybe we can change it to Refresh (It will revert all changes)
> Do you want to make a contribution to this small fix?

But I don't think it will revert all changes, will it? I mean, If a text says "revert all changes", to me this means: "Okay everything I have done till now, will be reverted from the database". I would change it to "Refresh - reverts all uncommitted changes"

**Comment by thanhlmm** [comment]
It will revert all pending changes. In fact, when the button is clicked, it refreshes all the states, so that all pending changes will also be reverted.

"Refresh - reverts all uncommitted changes" seems good. Let's do this

**Comment by thanhlmm** [comment]
A confirm modal should be good since all the changes will be reverted I think

**Comment by Berki2021** [comment]
> A confirm modal should be good since all the changes will be reverted I think

Yes

**Comment by Berki2021** [comment]
> A confirm modal should be good since all the changes will be reverted I think

How can I add the confirm modal? I already renamed the buttons

**Comment by thanhlmm** [comment]
https://garden.zendesk.com/components/modal

You can follow this guide to make a confirm modal

**Comment by thanhlmm** [comment]
https://github.com/thanhlmm/refi-app/blob/d9849ac8f6f40b760e9edc2081d1e6ffb6fcac5b/vite/src/atoms/hotkeys.ts#L73 should be a starting point to do

**Comment by thanhlmm** [comment]
Fixed in https://github.com/thanhlmm/refi-app/commit/72c4cee8a848b84d2711af31c47187aa9e8ae8a8
