### ISSUE TITLE
Feature Request Collapsable Json view

### ISSUE THREAD

**Issue by yotamishak** [thanhlmm/refi-app#35]
update json view for document view so fields can be collapsed

**Comment by thanhlmm** [comment]
Hi @yotamishak  thank you for your feedback.
But which type of document do you want to view as JSON. Do you mean the tree on the left? Because there is a JSON editor on the right side and you can collapse it

**Comment by yotamishak** [comment]
![image](https://user-images.githubusercontent.com/44552534/146160328-f35bf092-e074-415f-baf2-1501fe13f722.png)

I'm using your native mac app perhaps it's not implemented there? 
I am not talking about the collections on the right side but rather the actual document view on the left.
Like in the attached image, you can collapse fields of the JSON tree by clicking minus or plus(open or close) like in vscode or JetBrains products

**Comment by thanhlmm** [comment]
Fixed in https://github.com/thanhlmm/refi-app/commit/fb59302f06ac5710182b06233b9b0fc3fca993b9

Thanks @yotamishak for suggestion
