### ISSUE TITLE
Bug: Cannot update Emulator

### ISSUE THREAD

**Issue by Berki2021** [thanhlmm/refi-app#37]
I don't know what exactly I am doing wrong, but whatever I do, the app does not update the emulators data. Deleting, creating or changing any data does nothing (can't see the changes in google chrome "localhost:4000/firestore"

Version: Windows 10

**Comment by thanhlmm** [comment]
<img width="828" alt="Screen Shot 2022-01-29 at 17 39 41" src="https://user-images.githubusercontent.com/9281080/151657895-de1a2894-5c94-45e4-897a-1c727572fde8.png">
Hi @Berki2021 , I think you missed config the emulatar
