### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by zakblacki** [thanhlmm/refi-app#5]
Hi, does this work on windows ? it's not clear

**Comment by thanhlmm** [comment]
Hey @zakblacki you can download the window version at https://github.com/thanhlmm/refi-app/releases/tag/v0.0.9

<img width="1114" alt="Screen Shot 2021-08-04 at 09 00 06" src="https://user-images.githubusercontent.com/9281080/128109854-29cb61e1-ff5b-43fc-8744-b2ba8ef60ab8.png">

Thanks for using RefiApp :)

**Comment by zakblacki** [comment]
Thanks, dumb question  how do I get credentials file ? when I click on it nothing happen
![image](https://user-images.githubusercontent.com/29728429/128136149-7659f5c6-40fd-4d5b-a5b4-7f677942ee46.png)

**Comment by thanhlmm** [comment]
Sure. I got struggle building Window version with my new Mac book M1, will update you if I figure out how to do it

BTW, free free to create a issue if you think it can be improved

**Comment by zakblacki** [comment]
well the UI can be improved we could use a visible button for import data 
also there is no option to rename collection or duplicate 
also we could use option to move the column as we see fit  example : 
![image](https://user-images.githubusercontent.com/29728429/128137399-0dea04c2-d471-442c-9926-7b115791b2d9.png)


![Screenshot taken from Firefoo](https://user-images.githubusercontent.com/29728429/128137489-f51242c1-e3e4-4092-8f21-32df966b00c2.png)

**Comment by zakblacki** [comment]
Help Import CSV not working for me
