### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by danbars** [thanhlmm/refi-app#52]
Hello,

I've created a service account with (I think) proper permissions and I'm trying to connect.
However, after choosing the credentials file and hitting 'connect' I get this error message
<img width="419" alt="image" src="https://user-images.githubusercontent.com/6115771/154195084-f5ea458b-96af-49bd-b642-f7dd57883ad3.png">

Here are the roles that this account has:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/6115771/154195183-b59baca4-c479-46e0-a3f1-5b17dbf6b1cb.png">

What am I doing wrong?

Thanks

**Comment by thanhlmm** [comment]
Hi @danbars 

Thanks for using Refi App

Here is the instruction how to get the credential: https://www.notion.so/thanh-le/How-to-get-my-credential-file-781fb9bfa0cf479a81b72a272728808c

The app also h
<img width="871" alt="Screen Shot 2022-02-16 at 11 19 33 AM" src="https://user-images.githubusercontent.com/9281080/154195731-6119530a-afd9-4376-a66e-4bf0a138cd7c.png">
as a link to show you how to get it

Let me know if it works and Refi App fit your use cases :)

**Comment by danbars** [comment]
Hi, thanks for the quick response.
I have seen this link and followed it to create a new credential file, even though I've already had one.
I've opened this ticket after this wasn't successful...

BTW, I used the same file that I have created with another desktop client (Fireman), and it worked, so I'm sure the credentials were created properly.

**Comment by danbars** [comment]
This is how the file looks
<img width="881" alt="image" src="https://user-images.githubusercontent.com/6115771/154197649-02acb971-6997-429d-afbe-d22f474b5fc6.png">

**Comment by thanhlmm** [comment]
Hi the key file seems good. I also reproduce the same steps as the guide said and all seems fine.

Maybe you can test a new Firebase project. I think that you're missing some role to get access

**Comment by danbars** [comment]
I've listed the roles that this user has in the first post. Can you please confirm that these are the roles that you have?
Maybe I am missing something...

**Comment by thanhlmm** [comment]
To be honest, I don't know how to get the role from a service account file. I was playing with google cloud console for about 1 hour to find the right role 😅

**Comment by danbars** [comment]
You can't get the roles from the file itself.
You need to look at the "client_email" field from the file, and go to Firebase project settings > service accounts > "<number> service accounts"
<img width="363" alt="image" src="https://user-images.githubusercontent.com/6115771/154206181-67e20f2a-dccc-4fab-9c40-52a86abe501e.png">

This will open Google Cloud Console window. You are supposed to land on IAM & Admin > Permissions for project X

In the table, look for a Principal with the email address that you have on the file. Then further to the right you'll see its roles.

**Comment by thanhlmm** [comment]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/9281080/154213496-7c406ed5-07d0-464a-bb0a-7ad06ad71770.png">
Hey this is the service account permission

**Comment by danbars** [comment]
I've managed to fix it.
All I did was to open a new tab in Refi, and reconnect.
The first tab originally failed with a JSON that belonged to an account that was already revoked. But even after using a new json of a new account it kept failing. 
Perhaps there's a bug that the tab "remembers" the original file. 

Thank you anyway for the quick support!

**Comment by rafaelnobrekz** [comment]
Wow Thank you, I had the same exact issue. I first dropped whatever credential file I had here (which was fore Firebase Distribution), and after generating the right one, the tab kept failing! After opening a new one and dropping the new key, it worked fine.
