### ISSUE TITLE
Timestamp String

### ISSUE THREAD

**Issue by rgoodridge** [thanhlmm/refi-app#57]
When importing a Timestamp from a JSON file it always sets the field as a string as opposed to a timestamp.

Not sure if this is something that can be fixed?

**Comment by thanhlmm** [comment]
Hi @rgoodridge ,

You need to put the field value as `__Timestamp__2022-03-19T03:44:43.443Z` to make Refi app recognize as timestamp

I think you can do it with some Excel skill then export to CSV

**Comment by kgoransson** [comment]
Hhjkfvlklkvkjvckcbfjlckglccclcjljkkglklkkllkkkkllklklkklcbkllklkclkk
