### ISSUE TITLE
Renaming Tabs

### ISSUE THREAD

**Issue by caleb654** [thanhlmm/refi-app#58]
Thank you for such an amazing app! Just one thing would be awesome if I could rename the tabs up top because I often work between a couple different Firebase projects.

**Comment by thanhlmm** [comment]
Hi @caleb654 
I'm happy that you love it. Do you think if we use project name as tab name gonna works? I think default name could make the works lots easier than make the tab renamable

**Comment by thanhlmm** [comment]
It has been resolved in https://github.com/thanhlmm/refi-app/pull/59. Please upgrade to the latest version!
