### ISSUE TITLE
Source Code For How To Implement Tabs In Electron

### ISSUE THREAD

**Issue by meilechwieder** [thanhlmm/refi-app#6]
Hi you wrote [this](https://dev.to/thanhlm/electron-multiple-tabs-without-dealing-with-performance-2cma) blog post on electron tabs, but you didn't share how you did it. Can you do so? Thanks!

**Comment by thanhlmm** [comment]
Hi @meilechwieder, I'm going to open-source Refi App this month, so please stay tuned

**Comment by thanhlmm** [comment]
Refi app is open sourced now, you can check how Tabs is implemented in
- https://github.com/thanhlmm/refi-app/blob/main/vite/src/tabs.tsx
- https://github.com/thanhlmm/refi-app/blob/main/server/src/index.ts#L82

**Comment by thanhlmm** [comment]
Skeleton for high performance electorn tabs: https://github.com/thanhlmm/electron-multiple-tabs
