### ISSUE TITLE
Can't download the project getting this error-Error: Couldn't find windows app for app with ID 211201njqikvxkx

### ISSUE THREAD

**Issue by shubham-sancheti** [thanhlmm/refi-app#64]

**Comment by thanhlmm** [comment]
Hi @shubham-sancheti , can you add a screen shot regarding to the error?

**Comment by wmhseir3** [comment]
same issue following the link below. attached the screenshot as with the error.
Download link: https://dl.todesktop.com/211201njqikvxk
![ng_download](https://user-images.githubusercontent.com/55186251/168514774-761b5e89-194b-479c-93e5-c56dea06f214.jpg)
x

**Comment by Mistic92** [comment]
I'm getting the same error

**Comment by anjukarl** [comment]
Same error when clicking on link to download:
Error: Couldn't find windows app for app with ID 211201njqikvxkx

**Comment by thanhlmm** [comment]
Currently, the build doesn't support Windows, that's why you can not use Refi in Windows. I will make a window build this weekend.

**Comment by shubham-sancheti** [comment]
ok thanks

**Comment by thanhlmm** [comment]
Hi @shubham-sancheti @Mistic92 @anjukarl @wmhseir3 

After few hours trying, here is the window version :) : https://github.com/thanhlmm/refi-app/releases/tag/v0.0.17

Please let me know if we got any issue
