### ISSUE TITLE
Question about how refi-app works?

### ISSUE THREAD

**Issue by darewreck54** [thanhlmm/refi-app#71]
I could totally misunderstand the usage of this tool and a bit new to firestore, so please bear with me.  With this tool, I should be able to visualize the data in the emulator no?

I have
- firestore emulator running on port localhost:8003
- Runing a golang unit test to just insert a collection and documents into the localhost:8003
- Execute code to read from the emulator and it looks correct.  

```
func TestPut(t *testing.T) {
	ctx := context.Background()
	//db := newFirestoreTestClient(ctx)
	//fsClient := &firestoreClient{db: db}
	//SetFirestoreClient(fsClient)
	project := "project"
	os.Setenv("FIRESTORE_EMULATOR_HOST", "localhost:8003")
	client, err := firestore.NewClient(ctx, project)

	if value := os.Getenv("FIRESTORE_EMULATOR_HOST"); value != "" {
		log.Printf("Using Firestore Emulator: %s", value)
	}

	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()

	_, _, err = client.Collection("users").Add(ctx, map[string]interface{}{
		"first": "Ada",
		"last":  "Lovelace",
		"born":  1815,
	})

	if err != nil {
		log.Fatalf("Failed adding alovelace: %v", err)
	}

	iter := client.Collection("users").Documents(ctx)
	for {
		doc, err := iter.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			log.Fatalf("Failed to iterate: %v", err)
		}
		fmt.Println(doc.Data())
	}

}
```

output
```
=== RUN   TestPut
2022/07/10 16:52:57 pipeline_stage_metadata_test.go:23: Using Firestore Emulator: localhost:8003
map[born:1815 first:Ada last:Lovelace]
map[born:1815 first:Ada last:Lovelace]
map[born:1815 first:Ada last:Lovelace]
map[born:1815 first:Ada last:Lovelace]
map[born:1815 first:Ada last:Lovelace]
--- PASS: TestPut (0.04s)
PASS
```

However, When i try to refresh the refid app tool, once i connect successfully to localhost:8003, I would expect to see the collection or documents. but i'm not seeing anything.

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/16171726/178167323-9ea82127-29cc-46f8-8c7f-7751ed705418.png">

emulator firebase config:
```
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "y"
  },
  "emulators": {
    "firestore": {
      "port": 8003
    },
    "ui": {
      "enabled": true,
      "port": 4000
    }
  },
  "functions": {
    "source": "functions"
  }
}
```
Am i missing something?

Thanks,
Derek

**Comment by thanhlmm** [comment]
Hi Derek,

Thanks for asking, you need to make sure both RefiApp and your test script have the same `project-name` , if not the app can still connect bot they are not sharing the same data

**Comment by darewreck54** [comment]
Thanks!

I got thrown off at the connection screen.  I didn't know it was for the `Project Name` for the connection.  Thought it was just to name the connection type.

**Comment by thanhlmm** [comment]
Great, I have same issue before and though every project name is works on simulator
