### ISSUE TITLE
I don't know how to get credential file

### ISSUE THREAD

**Issue by narayanchoudhary** [thanhlmm/refi-app#8]
the link in the app not working. It opens a blank page.

**Comment by thanhlmm** [comment]
Hi @narayanchoudhary, you can get the guide here: https://www.notion.so/cuthanh/How-to-get-my-credential-file-781fb9bfa0cf479a81b72a272728808c

**Comment by narayanchoudhary** [comment]
> Hi @narayanchoudhary, you can get the guide here: https://www.notion.so/cuthanh/How-to-get-my-credential-file-781fb9bfa0cf479a81b72a272728808c


![Untitled](https://user-images.githubusercontent.com/12245209/143669978-278b8889-f7d7-4deb-8232-a6197f97ab7c.png)

**Comment by thanhlmm** [comment]
[How_to_get_my_credential_file.pdf](https://github.com/thanhlmm/refi-app/files/7611392/How_to_get_my_credential_file.pdf)

I put the guide here. I think your laptop is blocked to access Notion.so that why you see a blank page
