### ISSUE TITLE
Catalina support?

### ISSUE THREAD

**Issue by pentolbakso** [thanhlmm/refi-app#9]
Any plans to support Catalina on mac ?

**Comment by thanhlmm** [comment]
Hi @pentolbakso I should run on Catalina

Do you have any issues while using Refi App on Catalina?

**Comment by pentolbakso** [comment]
Yes, I can't run the app

<img width="730" alt="Screen Shot 2021-11-28 at 20 57 04" src="https://user-images.githubusercontent.com/12092714/143770917-cc4a41f6-d17d-4f73-a694-94edf18bac18.png">

**Comment by thanhlmm** [comment]
Hmm, seem like Electron is built based on macOS version. I will build a new version support Catalina tmr

Thanks for the issue

**Comment by thanhlmm** [comment]
Hmm. Seem like we can not build older version right now because of Electron-forge.

We need to move from Electron Forge to https://github.com/electron-userland/electron-builder which is can set minimum macOS version

**Comment by davej** [comment]
> Hmm. Seem like we can not build older version right now because of Electron-forge.
> 
> We need to move from Electron Forge to https://github.com/electron-userland/electron-builder which is can set minimum macOS version

BTW: Feel free to use [ToDesktop CLI](https://www.todesktop.com/cli). I'll make your app free while you are open source.

**Comment by thanhlmm** [comment]
@davej Awesome, I haven't known that before.
Look great to build Refi, I'm using Mac M1 and it is quite hard to build for other platforms LOL

**Comment by thanhlmm** [comment]
Hi @pentolbakso

https://dl.todesktop.com/211201njqikvxkx/builds/211208i3mvsqrbs

This is beta build for the fixing, would you mind helping me try it and confirm does this build really helps?

**Comment by pentolbakso** [comment]
@thanhlm27 Yes, the build is working on my Catalina machine
Thanks

**Comment by thanhlmm** [comment]
Awesome, I will release this version soon!

**Comment by thanhlmm** [comment]
Fixed in v0.0.11
